#ifndef MQL_AUTO_FORWARDS_INCLUDED_FB5929E3412D7326
#define MQL_AUTO_FORWARDS_INCLUDED_FB5929E3412D7326
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/1_CandleClassification.mq5

#line 169 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/1_CandleClassification.mq5"
CANDLE_TYPE ClassifyCandle(double open, double high, double low, double close, double currentATR, double bodyThreshold);
#line 200 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/1_CandleClassification.mq5"
double GetAverageRange(const int i, const int rates_total, const double& high[], const double& low[]);

#endif
