#ifndef MQL_AUTO_FORWARDS_INCLUDED_56089AAF8BF025F0
#define MQL_AUTO_FORWARDS_INCLUDED_56089AAF8BF025F0
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/2_FormationDetection.mq5

#line 44 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/2_FormationDetection.mq5"
double GetAverageRange(const int i, const int rates_total, const double &high[], const double &low[]);
#line 58 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/2_FormationDetection.mq5"
CandleType ClassifyCandle(const int i, const int rates_total, const double &open[], const double &high[], const double &low[], const double &close[]);

#endif
