#ifndef MQL_AUTO_FORWARDS_INCLUDED_9C3E2158FEE37E0B
#define MQL_AUTO_FORWARDS_INCLUDED_9C3E2158FEE37E0B
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/3_ZoneDrawing.mq5

#line 29 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/3_ZoneDrawing.mq5"
double GetAverageRange(const int i, const int rates_total, const double &high[], const double &low[]);
#line 43 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/3_ZoneDrawing.mq5"
CandleType ClassifyCandle(const int i, const int rates_total, const double &open[], const double &high[], const double &low[], const double &close[]);
#line 61 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/3_ZoneDrawing.mq5"
void ClearZoneObjects();
#line 72 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/3_ZoneDrawing.mq5"
void BuildZone(const int leftType, const int rightType, const int baseStart, const int baseEnd, const datetime &time[], const double &open[], const double &high[], const double &low[], const double &close[]);

#endif
