#ifndef MQL_AUTO_FORWARDS_INCLUDED_75FAC95406286830
#define MQL_AUTO_FORWARDS_INCLUDED_75FAC95406286830
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/AD.mq5

#line 66 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/AD.mq5"
void Calculate(const int rates_total, const int pos, const double &high[], const double &low[], const double &close[], const long &volume[]);

#endif
