#ifndef MQL_AUTO_FORWARDS_INCLUDED_5736C9BF46CE4B97
#define MQL_AUTO_FORWARDS_INCLUDED_5736C9BF46CE4B97
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/AMA.mq5

#line 120 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/AMA.mq5"
double CalculateER(const int pos, const double& price[]);

#endif
