#ifndef MQL_AUTO_FORWARDS_INCLUDED_0E274D5830F0D8F0
#define MQL_AUTO_FORWARDS_INCLUDED_0E274D5830F0D8F0
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5

#line 72 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
void CalculateZones(const int rates_total, const int prev_calculated, const double& low[], const double& high[], const double& close[], const datetime& time[]);
#line 139 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
bool ZoneExistsNearby(double price, bool isDemand);
#line 171 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
bool IsOverlap(double a_top, double a_bottom, double b_top, double b_bottom);
#line 178 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
bool IsNear(double a_top, double a_bottom, double b_top, double b_bottom);
#line 188 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
void MergeZones();
#line 241 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/BasicS&D.mq5"
void ClearOldZones();

#endif
