#ifndef MQL_AUTO_FORWARDS_INCLUDED_8C42466C1D79CFE6
#define MQL_AUTO_FORWARDS_INCLUDED_8C42466C1D79CFE6
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/BB.mq5

#line 128 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/BB.mq5"
double StdDev_Func(const int position, const double &price[], const double &ma_price[], const int period);

#endif
