#ifndef MQL_AUTO_FORWARDS_INCLUDED_6CF439B63C031269
#define MQL_AUTO_FORWARDS_INCLUDED_6CF439B63C031269
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/BitonicSort.mq5

#line 24 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/BitonicSort.mq5"
resource as string cl_program void QuickSortAscending(float &array[], int first, int last);
#line 72 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/BitonicSort.mq5"
bool QuickSort_CPU(float &data_array[], ulong &time_cpu);
#line 88 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/BitonicSort.mq5"
bool BitonicSort_GPU(COpenCL &OpenCL, float &data_array[], ulong &time_gpu);
#line 149 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/BitonicSort.mq5"
bool PrepareDataArray(long global_memory_size, float &data[], int &data_count);

#endif
