#ifndef MQL_AUTO_FORWARDS_INCLUDED_55D5C3F8AD2D993C
#define MQL_AUTO_FORWARDS_INCLUDED_55D5C3F8AD2D993C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5

#line 147 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool CheckState();
#line 183 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool PositionOpen();
#line 274 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
void CloseBySignal(int type_close);
#line 324 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
void CloseByTime();
#line 360 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool PositionExist(int signal_direction);
#line 414 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool PositionExpiredByTimeExist();
#line 445 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
int BarsHold(datetime open_time);
#line 466 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double Open(int index);
#line 478 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double Close(int index);
#line 490 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double Low(int index);
#line 502 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double High(int index);
#line 514 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double MidPoint(int index);
#line 521 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double MidOpenClose(int index);
#line 528 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double AvgBody(int index);
#line 540 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool CheckPattern();
#line 582 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool CheckConfirmation();
#line 617 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
bool CheckCloseSignal();
#line 646 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BlackCrows WhiteSoldiers MFI.mq5"
double MFI(int index);

#endif
