#ifndef MQL_AUTO_FORWARDS_INCLUDED_06B41ABB95B485DE
#define MQL_AUTO_FORWARDS_INCLUDED_06B41ABB95B485DE
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5

#line 149 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool CheckState();
#line 185 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool PositionOpen();
#line 276 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
void CloseBySignal(int type_close);
#line 326 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
void CloseByTime();
#line 362 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool PositionExist(int signal_direction);
#line 416 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool PositionExpiredByTimeExist();
#line 448 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
int BarsHold(datetime open_time);
#line 469 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double Open(int index);
#line 481 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double Close(int index);
#line 493 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double Low(int index);
#line 505 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double High(int index);
#line 517 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double MidPoint(int index);
#line 524 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double MidOpenClose(int index);
#line 531 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double AvgBody(int index);
#line 543 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool CheckPattern();
#line 585 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool CheckConfirmation();
#line 620 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
bool CheckCloseSignal();
#line 651 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines Stoch.mq5"
double StochSignal(int index);

#endif
