#ifndef MQL_AUTO_FORWARDS_INCLUDED_4A48FB3C5EA21F0E
#define MQL_AUTO_FORWARDS_INCLUDED_4A48FB3C5EA21F0E
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5

#line 146 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool CheckState();
#line 182 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool PositionOpen();
#line 273 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
void CloseBySignal(int type_close);
#line 323 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
void CloseByTime();
#line 359 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool PositionExist(int signal_direction);
#line 413 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool PositionExpiredByTimeExist();
#line 444 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
int BarsHold(datetime open_time);
#line 465 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double Open(int index);
#line 477 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double Close(int index);
#line 489 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double Low(int index);
#line 501 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double High(int index);
#line 513 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double MidPoint(int index);
#line 520 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double MidOpenClose(int index);
#line 527 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double AvgBody(int index);
#line 539 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool CheckPattern();
#line 577 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool CheckConfirmation();
#line 612 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
bool CheckCloseSignal();
#line 641 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish MeetingLines MFI.mq5"
double MFI(int index);

#endif
