#ifndef MQL_AUTO_FORWARDS_INCLUDED_6A8C796F5B0392D2
#define MQL_AUTO_FORWARDS_INCLUDED_6A8C796F5B0392D2
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5

#line 161 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool CheckState();
#line 197 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool PositionOpen();
#line 288 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
void CloseBySignal(int type_close);
#line 338 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
void CloseByTime();
#line 374 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool PositionExist(int signal_direction);
#line 428 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool PositionExpiredByTimeExist();
#line 460 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
int BarsHold(datetime open_time);
#line 481 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double Open(int index);
#line 493 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double Close(int index);
#line 505 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double Low(int index);
#line 517 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double High(int index);
#line 529 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double MidPoint(int index);
#line 536 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double MidOpenClose(int index);
#line 543 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double AvgBody(int index);
#line 555 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool CheckPattern();
#line 597 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool CheckConfirmation();
#line 632 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
bool CheckCloseSignal();
#line 663 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double StochSignal(int index);
#line 677 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing Stoch.mq5"
double CloseAvg(int index);

#endif
