#ifndef MQL_AUTO_FORWARDS_INCLUDED_887D5487A86E9C22
#define MQL_AUTO_FORWARDS_INCLUDED_887D5487A86E9C22
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5

#line 158 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool CheckState();
#line 194 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool PositionOpen();
#line 285 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
void CloseBySignal(int type_close);
#line 335 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
void CloseByTime();
#line 371 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool PositionExist(int signal_direction);
#line 425 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool PositionExpiredByTimeExist();
#line 456 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
int BarsHold(datetime open_time);
#line 477 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double Open(int index);
#line 489 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double Close(int index);
#line 501 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double Low(int index);
#line 513 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double High(int index);
#line 525 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double MidPoint(int index);
#line 532 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double MidOpenClose(int index);
#line 539 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double AvgBody(int index);
#line 551 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool CheckPattern();
#line 593 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool CheckConfirmation();
#line 628 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
bool CheckCloseSignal();
#line 657 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double RSI(int index);
#line 671 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/BullishBearish Engulfing RSI.mq5"
double CloseAvg(int index);

#endif
