#ifndef MQL_AUTO_FORWARDS_INCLUDED_3DA0F1B557154CBF
#define MQL_AUTO_FORWARDS_INCLUDED_3DA0F1B557154CBF
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5

#line 145 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
void PIPCreate();
#line 159 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
void PIPDelete();
#line 173 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
void PIPSetParams();
#line 277 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
void PIPHideChart();
#line 287 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
bool StrToPeriod(const string strper, ENUM_TIMEFRAMES& period);
#line 361 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/ChartInChart/ChartInChart.mq5"
bool PeriodToStr(ENUM_TIMEFRAMES period, string& strper);

#endif
