#ifndef MQL_AUTO_FORWARDS_INCLUDED_640BDB5E405FA889
#define MQL_AUTO_FORWARDS_INCLUDED_640BDB5E405FA889
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/CHO.mq5

#line 97 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/CHO.mq5"
double AD(double high, double low, double close, long volume);
#line 113 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/CHO.mq5"
void AverageOnArray(const int mode, const int rates_total, const int prev_calculated, const int begin, const int period, const double& source[], double& destination[]);

#endif
