#ifndef MQL_AUTO_FORWARDS_INCLUDED_A75429CE0CD45EEA
#define MQL_AUTO_FORWARDS_INCLUDED_A75429CE0CD45EEA
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ColorBars.mq5


#endif
