#ifndef MQL_AUTO_FORWARDS_INCLUDED_562642477C1A5589
#define MQL_AUTO_FORWARDS_INCLUDED_562642477C1A5589
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ColorLine.mq5

#line 124 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ColorLine.mq5"
int getIndexOfColor(const int i);

#endif
