#ifndef MQL_AUTO_FORWARDS_INCLUDED_27F882C6369D8D00
#define MQL_AUTO_FORWARDS_INCLUDED_27F882C6369D8D00
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Controls/Controls.mq5


#endif
