#ifndef MQL_AUTO_FORWARDS_INCLUDED_554A25C9074FD4A5
#define MQL_AUTO_FORWARDS_INCLUDED_554A25C9074FD4A5
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Correlation Matrix 3D/Correlation Matrix 3D.mq5

#line 952 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Correlation Matrix 3D/Correlation Matrix 3D.mq5"
int GetTimeframeMinutes(ENUM_TIMEFRAMES timeframe);

#endif
