#ifndef MQL_AUTO_FORWARDS_INCLUDED_4BBFC2F23D4AF718
#define MQL_AUTO_FORWARDS_INCLUDED_4BBFC2F23D4AF718
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Custom Moving Average.mq5

#line 95 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Custom Moving Average.mq5"
void CalculateSimpleMA(int rates_total, int prev_calculated, int begin, const double &price[]);
#line 121 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Custom Moving Average.mq5"
void CalculateEMA(int rates_total, int prev_calculated, int begin, const double &price[]);
#line 142 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Custom Moving Average.mq5"
void CalculateLWMA(int rates_total, int prev_calculated, int begin, const double &price[]);
#line 176 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Custom Moving Average.mq5"
void CalculateSmoothedMA(int rates_total, int prev_calculated, int begin, const double &price[]);

#endif
