#ifndef MQL_AUTO_FORWARDS_INCLUDED_B26B343500C5792D
#define MQL_AUTO_FORWARDS_INCLUDED_B26B343500C5792D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5

#line 157 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool CheckState();
#line 193 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool PositionOpen();
#line 284 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
void CloseBySignal(int type_close);
#line 334 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
void CloseByTime();
#line 370 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool PositionExist(int signal_direction);
#line 424 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool PositionExpiredByTimeExist();
#line 454 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
int BarsHold(datetime open_time);
#line 475 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double Open(int index);
#line 487 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double Close(int index);
#line 499 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double Low(int index);
#line 511 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double High(int index);
#line 523 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double MidPoint(int index);
#line 530 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double MidOpenClose(int index);
#line 537 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double AvgBody(int index);
#line 549 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool CheckPattern();
#line 593 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool CheckConfirmation();
#line 628 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
bool CheckCloseSignal();
#line 657 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double CCI(int index);
#line 671 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine CCI.mq5"
double CloseAvg(int index);

#endif
