#ifndef MQL_AUTO_FORWARDS_INCLUDED_C4FDB41CED54E786
#define MQL_AUTO_FORWARDS_INCLUDED_C4FDB41CED54E786
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5

#line 157 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool CheckState();
#line 193 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool PositionOpen();
#line 284 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
void CloseBySignal(int type_close);
#line 333 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
void CloseByTime();
#line 369 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool PositionExist(int signal_direction);
#line 423 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool PositionExpiredByTimeExist();
#line 453 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
int BarsHold(datetime open_time);
#line 474 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double Open(int index);
#line 486 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double Close(int index);
#line 498 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double Low(int index);
#line 510 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double High(int index);
#line 522 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double MidPoint(int index);
#line 529 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double MidOpenClose(int index);
#line 536 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double AvgBody(int index);
#line 548 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool CheckPattern();
#line 592 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool CheckConfirmation();
#line 627 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
bool CheckCloseSignal();
#line 656 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double MFI(int index);
#line 670 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine MFI.mq5"
double CloseAvg(int index);

#endif
