#ifndef MQL_AUTO_FORWARDS_INCLUDED_00400653626B8008
#define MQL_AUTO_FORWARDS_INCLUDED_00400653626B8008
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5

#line 160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool CheckState();
#line 196 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool PositionOpen();
#line 287 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
void CloseBySignal(int type_close);
#line 337 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
void CloseByTime();
#line 373 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool PositionExist(int signal_direction);
#line 427 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool PositionExpiredByTimeExist();
#line 457 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
int BarsHold(datetime open_time);
#line 478 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double Open(int index);
#line 490 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double Close(int index);
#line 502 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double Low(int index);
#line 514 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double High(int index);
#line 526 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double MidPoint(int index);
#line 533 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double MidOpenClose(int index);
#line 540 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double AvgBody(int index);
#line 552 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool CheckPattern();
#line 596 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool CheckConfirmation();
#line 631 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
bool CheckCloseSignal();
#line 662 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double StochSignal(int index);
#line 676 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/DarkCloud PiercingLine Stoch.mq5"
double CloseAvg(int index);

#endif
