#ifndef MQL_AUTO_FORWARDS_INCLUDED_745DDB4124B5A2AB
#define MQL_AUTO_FORWARDS_INCLUDED_745DDB4124B5A2AB
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/DEMA.mq5


#endif
