#ifndef MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
#define MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5

#line 129 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
EngulfInfo FindAndDrawEngulfZone(const int i, const int rates_total, const Candle& candles[]);
#line 153 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
int HtfBarToChartIndex(const datetime bar_time, const int rates_total);
#line 161 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void DrawEngulfZone(const datetime bar_time, const double zone_high, const double zone_low);
#line 178 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void DrawDbdBaseZone(const EngulfInfo& engulf);
#line 204 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
string EngulfZoneNameFromTime(const datetime bar_time);
#line 208 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void ClearZoneObjects();

#endif
