#ifndef MQL_AUTO_FORWARDS_INCLUDED_FC96401E800B778C
#define MQL_AUTO_FORWARDS_INCLUDED_FC96401E800B778C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5

#line 70 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool IsNewAnalysisBar();
#line 82 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool HasOpenPosition();
#line 96 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool OpenSell(const DbdSignal& signal);
#line 113 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void UpdateDebugDraw(const bool hasFullDbdSignal);
#line 130 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void ClearDebugObjects();
#line 145 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void DrawEngulfDebugZone(const HtfEngulfInfo& engulf);
#line 164 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void DrawEngulfDebugArrow(const HtfEngulfInfo& engulf);
#line 182 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void DrawDbdDebugZone(const DbdSignal& signal);

#endif
