#ifndef MQL_AUTO_FORWARDS_INCLUDED_FC96401E800B778C
#define MQL_AUTO_FORWARDS_INCLUDED_FC96401E800B778C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5

#line 83 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void RemoveOutZoneLtfEngulfs();
#line 148 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool IsNewAnalysisBar();
#line 160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool HasOpenPosition();
#line 174 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool OpenSell(const DbdSignal& signal);
#line 191 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void FindAndDrawEngulfZones();
#line 213 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
string BuildEngulfArrowName(const string scope, const int index, const datetime barTime);
#line 217 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
bool DrawEngulfArrow(const EngulfInfo& engulf, const string scope, const int index);
#line 251 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void DrawEngulfZone(const EngulfInfo& engulf);
#line 268 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void DrawDbdBaseZone(const EngulfInfo& engulf);
#line 294 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/EngulfDbdEA.mq5"
void ClearEngulfZoneObjects();

#endif
