#ifndef MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
#define MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5

#line 103 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void ClearZoneObjects();
#line 117 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
CandleType BearOrBull(const double open, const double close);

#endif
