#ifndef MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
#define MQL_AUTO_FORWARDS_INCLUDED_B7F74A678563C45D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5

#line 106 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void UpdateEngulfChartAtBar(const int i, const int rates_total, const double& htf_open[], const double& htf_high[], const double& htf_low[], const double& htf_close[], const datetime& htf_time[]);
#line 132 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
int HtfBarToChartIndex(const datetime bar_time, const int rates_total);
#line 140 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void ClearZoneObjects();
#line 159 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void BuildEngulfZone(const datetime bar_time, const double zone_high, const double zone_low);
#line 176 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
void DrawDbdBaseZone(const DbdSignal& signal);
#line 197 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/engulf.mq5"
string EngulfZoneNameFromTime(const datetime bar_time);

#endif
