#ifndef MQL_AUTO_FORWARDS_INCLUDED_D967793B0A6DC7BF
#define MQL_AUTO_FORWARDS_INCLUDED_D967793B0A6DC7BF
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Advisors/ExpertMAMA.mq5


#endif
