#ifndef MQL_AUTO_FORWARDS_INCLUDED_3111832D299E9442
#define MQL_AUTO_FORWARDS_INCLUDED_3111832D299E9442
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5

#line 28 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
define FFT_DIRECTION 1 void fft(const int N, float &x_real[], float &x_imag[], float &X_real[], float &X_imag[]);
#line 40 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
void ifft(const int N, float &x_real[], float &x_imag[], float &X_real[], float &X_imag[]);
#line 62 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
void fft_rec(const int N, const int offset, const int delta, float &x_real[], float &x_imag[], float &X_real[], float &X_imag[], float &XX_real[], float &XX_imag[]);
#line 104 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
bool FFT_CPU(int direction, int power, float &data_real[], float &data_imag[], ulong &time_cpu);
#line 131 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
bool ExecutionWait(COpenCL& OpenCL, int kernel_index);
#line 155 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/FFT.mq5"
bool FFT_GPU(int direction, int power, float &data_real[], float &data_imag[], ulong &time_gpu);

#endif
