#ifndef MQL_AUTO_FORWARDS_INCLUDED_9E1C8BAF67BFBBCC
#define MQL_AUTO_FORWARDS_INCLUDED_9E1C8BAF67BFBBCC
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Gator_2.mq5

#line 232 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Gator_2.mq5"
bool CheckForInput();

#endif
