#ifndef MQL_AUTO_FORWARDS_INCLUDED_6F7CDBF63438534F
#define MQL_AUTO_FORWARDS_INCLUDED_6F7CDBF63438534F
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Gator.mq5

#line 244 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Gator.mq5"
bool CheckForInput();

#endif
