#ifndef MQL_AUTO_FORWARDS_INCLUDED_674EA4406969283C
#define MQL_AUTO_FORWARDS_INCLUDED_674EA4406969283C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5

#line 157 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool CheckState();
#line 193 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool PositionOpen();
#line 284 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
void CloseBySignal(int type_close);
#line 334 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
void CloseByTime();
#line 370 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool PositionExist(int signal_direction);
#line 424 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool PositionExpiredByTimeExist();
#line 456 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
int BarsHold(datetime open_time);
#line 477 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double Open(int index);
#line 489 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double Close(int index);
#line 501 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double Low(int index);
#line 513 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double High(int index);
#line 525 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double MidPoint(int index);
#line 532 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double MidOpenClose(int index);
#line 539 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double AvgBody(int index);
#line 551 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool CheckPattern();
#line 590 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool CheckConfirmation();
#line 625 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
bool CheckCloseSignal();
#line 654 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double MFI(int index);
#line 668 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer MFI.mq5"
double CloseAvg(int index);

#endif
