#ifndef MQL_AUTO_FORWARDS_INCLUDED_41711F159A5A616C
#define MQL_AUTO_FORWARDS_INCLUDED_41711F159A5A616C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5

#line 160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool CheckState();
#line 196 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool PositionOpen();
#line 287 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
void CloseBySignal(int type_close);
#line 337 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
void CloseByTime();
#line 373 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool PositionExist(int signal_direction);
#line 427 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool PositionExpiredByTimeExist();
#line 458 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
int BarsHold(datetime open_time);
#line 479 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double Open(int index);
#line 491 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double Close(int index);
#line 503 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double Low(int index);
#line 515 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double High(int index);
#line 527 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double MidPoint(int index);
#line 534 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double MidOpenClose(int index);
#line 541 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double AvgBody(int index);
#line 553 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool CheckPattern();
#line 592 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool CheckConfirmation();
#line 627 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
bool CheckCloseSignal();
#line 658 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double StochSignal(int index);
#line 672 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/HangingMan Hammer Stoch.mq5"
double CloseAvg(int index);

#endif
