#ifndef MQL_AUTO_FORWARDS_INCLUDED_5811E042D82F0B90
#define MQL_AUTO_FORWARDS_INCLUDED_5811E042D82F0B90
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Ichimoku.mq5

#line 105 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Ichimoku.mq5"
double Highest(const double& array[], const int range, int from_index);
#line 119 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Ichimoku.mq5"
double Lowest(const double& array[], const int range, int from_index);

#endif
