#ifndef MQL_AUTO_FORWARDS_INCLUDED_03D2A1A2E8AB515F
#define MQL_AUTO_FORWARDS_INCLUDED_03D2A1A2E8AB515F
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MarketFacilitationIndex.mq5

#line 72 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MarketFacilitationIndex.mq5"
void CalculateMFI(const int start, const int rates_total, const double &high[], const double &low[], const long &volume[]);

#endif
