#ifndef MQL_AUTO_FORWARDS_INCLUDED_63C6D0E806DD4534
#define MQL_AUTO_FORWARDS_INCLUDED_63C6D0E806DD4534
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/MarketProfile.mq5

#line 201 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/MarketProfile.mq5"
void DrawBox(string bar_prefix, double price, datetime time1, datetime time2, color clr);

#endif
