#ifndef MQL_AUTO_FORWARDS_INCLUDED_B4FBB1B5ECFF40AC
#define MQL_AUTO_FORWARDS_INCLUDED_B4FBB1B5ECFF40AC
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/MarketProfile Canvas.mq5

#line 189 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/MarketProfile Canvas.mq5"
CMarketProfile* GetMarketProfileByDate(string prefix, datetime time);

#endif
