#ifndef MQL_AUTO_FORWARDS_INCLUDED_DC990775F98E416A
#define MQL_AUTO_FORWARDS_INCLUDED_DC990775F98E416A
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/MarketStructureExample.mq5

#line 72 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/MarketStructureExample.mq5"
bool BuildCandles(const int rates_total, const datetime& time[], const double& open[], const double& high[], const double& low[], const double& close[], Candle& candles[]);

#endif
