#ifndef MQL_AUTO_FORWARDS_INCLUDED_6AA10367F801E699
#define MQL_AUTO_FORWARDS_INCLUDED_6AA10367F801E699
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Math 3D Morpher/Math 3D Morpher.mq5

#line 40 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Math 3D Morpher/Math 3D Morpher.mq5"
define CAMERA_ANGLE_Y_SPEED 0.3f bool NormalizeData(double &data[], double &data_min, double &data_max);

#endif
