#ifndef MQL_AUTO_FORWARDS_INCLUDED_38A17E927CA3EBC7
#define MQL_AUTO_FORWARDS_INCLUDED_38A17E927CA3EBC7
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MFI.mq5

#line 85 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MFI.mq5"
void CalculateMFI(const int start_position, const int rates_total, const double &high[], const double &low[], const double &close[], const long &volume[]);
#line 116 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MFI.mq5"
double TypicalPrice(const double high_price, const double low_price, const double close_price);

#endif
