#ifndef MQL_AUTO_FORWARDS_INCLUDED_1F68A93C8F77D38A
#define MQL_AUTO_FORWARDS_INCLUDED_1F68A93C8F77D38A
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/MI.mq5


#endif
