#ifndef MQL_AUTO_FORWARDS_INCLUDED_1ACE99873856D023
#define MQL_AUTO_FORWARDS_INCLUDED_1ACE99873856D023
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5

#line 149 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool CheckState();
#line 185 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool PositionOpen();
#line 276 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
void CloseBySignal(int type_close);
#line 326 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
void CloseByTime();
#line 362 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool PositionExist(int signal_direction);
#line 416 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool PositionExpiredByTimeExist();
#line 447 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
int BarsHold(datetime open_time);
#line 468 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double Open(int index);
#line 480 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double Close(int index);
#line 492 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double Low(int index);
#line 504 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double High(int index);
#line 516 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double MidPoint(int index);
#line 523 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double MidOpenClose(int index);
#line 530 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double AvgBody(int index);
#line 542 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool CheckPattern();
#line 614 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool CheckConfirmation();
#line 649 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
bool CheckCloseSignal();
#line 680 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji Stoch.mq5"
double StochSignal(int index);

#endif
