#ifndef MQL_AUTO_FORWARDS_INCLUDED_A31335D903AEE67D
#define MQL_AUTO_FORWARDS_INCLUDED_A31335D903AEE67D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5

#line 146 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool CheckState();
#line 182 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool PositionOpen();
#line 273 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
void CloseBySignal(int type_close);
#line 323 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
void CloseByTime();
#line 359 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool PositionExist(int signal_direction);
#line 413 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool PositionExpiredByTimeExist();
#line 443 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
int BarsHold(datetime open_time);
#line 464 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double Open(int index);
#line 476 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double Close(int index);
#line 488 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double Low(int index);
#line 500 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double High(int index);
#line 512 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double MidPoint(int index);
#line 519 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double MidOpenClose(int index);
#line 526 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double AvgBody(int index);
#line 538 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool CheckPattern();
#line 610 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool CheckConfirmation();
#line 645 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
bool CheckCloseSignal();
#line 674 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Free Robots/MorningEvening StarDoji CCI.mq5"
double CCI(int index);

#endif
