#ifndef MQL_AUTO_FORWARDS_INCLUDED_A4EB5E710BD538BE
#define MQL_AUTO_FORWARDS_INCLUDED_A4EB5E710BD538BE
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Moving Average/Moving Average.mq5

#line 25 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Moving Average/Moving Average.mq5"
define MA_MAGIC 1234501 double TradeSizeOptimized(void);
#line 89 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Moving Average/Moving Average.mq5"
void CheckForOpen(void);
#line 130 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Moving Average/Moving Average.mq5"
void CheckForClose(void);
#line 167 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Examples/Moving Average/Moving Average.mq5"
bool SelectPosition();

#endif
