#ifndef MQL_AUTO_FORWARDS_INCLUDED_698A85F3B1C1A612
#define MQL_AUTO_FORWARDS_INCLUDED_698A85F3B1C1A612
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/OBV.mq5

#line 68 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/OBV.mq5"
void CalculateOBV(int start_pos, int rates_total, const double& close[], const long& volume[]);

#endif
