#ifndef MQL_AUTO_FORWARDS_INCLUDED_F2FE92EE293015AB
#define MQL_AUTO_FORWARDS_INCLUDED_F2FE92EE293015AB
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/OsMA.mq5


#endif
