#ifndef MQL_AUTO_FORWARDS_INCLUDED_D5ED9C7FD7134A6C
#define MQL_AUTO_FORWARDS_INCLUDED_D5ED9C7FD7134A6C
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/Parabolic Channel.mq5

#line 159 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/Parabolic Channel.mq5"
void ShowPriceLevels(datetime time, int last_index);
#line 168 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Free Indicators/Parabolic Channel.mq5"
bool ShowRightPrice(const string name, datetime time, double price, color clr);

#endif
