#ifndef MQL_AUTO_FORWARDS_INCLUDED_EEE8DC17DB801F13
#define MQL_AUTO_FORWARDS_INCLUDED_EEE8DC17DB801F13
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ParabolicSAR.mq5

#line 181 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ParabolicSAR.mq5"
double GetHigh(int curr_pos, int start, const double& high[]);
#line 194 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ParabolicSAR.mq5"
double GetLow(int curr_pos, int start, const double& low[]);

#endif
