#ifndef MQL_AUTO_FORWARDS_INCLUDED_97D75E45DA433D4E
#define MQL_AUTO_FORWARDS_INCLUDED_97D75E45DA433D4E
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/Canvas/Charts/PieChartSample.mq5

#line 93 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/Canvas/Charts/PieChartSample.mq5"
uint RandomRGB(void);

#endif
