#ifndef MQL_AUTO_FORWARDS_INCLUDED_66381E5B8998E93D
#define MQL_AUTO_FORWARDS_INCLUDED_66381E5B8998E93D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/PositionInfo/PositionInfoSample.mq5


#endif
