#ifndef MQL_AUTO_FORWARDS_INCLUDED_894DD2E3C421D576
#define MQL_AUTO_FORWARDS_INCLUDED_894DD2E3C421D576
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Price_Channel.mq5

#line 87 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Price_Channel.mq5"
double Highest(const double& array[], const int range, const int from_index);
#line 98 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Price_Channel.mq5"
double Lowest(const double& array[], const int range, const int from_index);

#endif
