#ifndef MQL_AUTO_FORWARDS_INCLUDED_C121E185D3C6E18D
#define MQL_AUTO_FORWARDS_INCLUDED_C121E185D3C6E18D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/PVT.mq5

#line 70 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/PVT.mq5"
void CalculatePVT(const int pos, const int rates_total, const double& close[], const long& volume[]);

#endif
