#ifndef MQL_AUTO_FORWARDS_INCLUDED_F07F39E4C1412174
#define MQL_AUTO_FORWARDS_INCLUDED_F07F39E4C1412174
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/Remnant 3D/Remnant 3D.mq5


#endif
