#ifndef MQL_AUTO_FORWARDS_INCLUDED_ED8F13E4ACEEB64B
#define MQL_AUTO_FORWARDS_INCLUDED_ED8F13E4ACEEB64B
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5

#line 192 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool IsNewBar();
#line 206 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool ReadLatestZones(double &demandLow, double &supplyHigh);
#line 243 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
void ManageEntries(const bool inDemand, const bool inSupply, const double ask, const double bid, const double demandLow, const double supplyHigh);
#line 327 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool HasOpenPosition();
#line 346 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
ENUM_POSITION_TYPE CurrentPositionType();
#line 365 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool CloseCurrentPosition();
#line 391 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool OpenBuy(const double ask);
#line 414 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool OpenSell(const double bid);
#line 437 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
bool TrendAllows(const bool isBuy);
#line 461 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
long ZoneKey(const double zonePrice);
#line 513 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
void UpdateDbSummary();
#line 548 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/SDZoneBacktestEA.mq5"
void PrintStats();

#endif
