#ifndef MQL_AUTO_FORWARDS_INCLUDED_814673FCB92838F0
#define MQL_AUTO_FORWARDS_INCLUDED_814673FCB92838F0
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Seascape/Seascape.mq5

#line 17 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Seascape/Seascape.mq5"
bool ModelInitialize(int &cl_ctx, int &cl_prg, int &cl_krn, int &cl_mem);
#line 76 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Seascape/Seascape.mq5"
bool ModelResize(const int cl_ctx, const int cl_krn, int &cl_mem);
#line 108 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Seascape/Seascape.mq5"
void ModelShutdown(int cl_ctx, int cl_prg, int cl_krn, int cl_mem);

#endif
