#ifndef MQL_AUTO_FORWARDS_INCLUDED_7CB9302E4A4BBC52
#define MQL_AUTO_FORWARDS_INCLUDED_7CB9302E4A4BBC52
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/ObjectSphere/SphereSample.mq5

#line 32 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/ObjectSphere/SphereSample.mq5"
int Init(void);
#line 55 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/ObjectSphere/SphereSample.mq5"
void Deinit(void);

#endif
