#ifndef MQL_AUTO_FORWARDS_INCLUDED_B6D5DCD0BEED44C8
#define MQL_AUTO_FORWARDS_INCLUDED_B6D5DCD0BEED44C8
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/StdDev.mq5

#line 121 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/StdDev.mq5"
double StdDevFunc(const double &price[], const double &ma_price[], const int position);

#endif
