#ifndef MQL_AUTO_FORWARDS_INCLUDED_211402CED31D2CEB
#define MQL_AUTO_FORWARDS_INCLUDED_211402CED31D2CEB
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5

#line 34 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
include <Math\Fuzzy\SugenoFuzzySystem.mqh> bool Test_NormalCombinationMembershipFunction();
#line 67 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_GeneralizedBellShapedMembershipFunction();
#line 91 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_SigmoidalMembershipFunction();
#line 114 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_ProductTwoSigmoidalMembershipFunctions();
#line 140 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_TrapezoidMembershipFunction();
#line 173 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_NormalMembershipFunction();
#line 196 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_TriangularMembershipFunction();
#line 232 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_ConstantMembershipFunction();
#line 254 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_P_S_Z_ShapedMembershipFunction();
#line 277 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_Bisector();
#line 295 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_Centroid();
#line 322 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_Defuzzification();
#line 374 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_TipingProblem();
#line 439 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool Test_TypicalFuzzyControlSystem();
#line 511 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
void AddSugenoFuzzyRule(CSugenoFuzzySystem *fs, CFuzzyVariable *fv1, CFuzzyVariable *fv2, CSugenoVariable *sv, const string value1, const string value2, const string result);
#line 527 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool TestMembersipFunctions(const string test_name);
#line 573 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool TestDefuzzificationMethods(const string test_name);
#line 595 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
bool TestFuzzySystems(const string test_name);
#line 613 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
void TestFuzzy(int &tests_performed, int &tests_passed);
#line 643 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Fuzzy/TestFuzzy.mq5"
void UnitTests(const string package_name);

#endif
