#ifndef MQL_AUTO_FORWARDS_INCLUDED_83EB1111EA0F8A6B
#define MQL_AUTO_FORWARDS_INCLUDED_83EB1111EA0F8A6B
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Alglib/TestInterfaces.mq5


#endif
