#ifndef MQL_AUTO_FORWARDS_INCLUDED_C877D8FABF6E492B
#define MQL_AUTO_FORWARDS_INCLUDED_C877D8FABF6E492B
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5

#line 12 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
include <Generic\HashSet.mqh> bool TestMisc_Constructor(const int count);
#line 48 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestMisc_Contains(const int count);
#line 80 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestMisc_Add(const int count);
#line 106 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestMisc(const string test_name);
#line 128 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestFind_Max(const int count);
#line 153 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestFind_Min(const int count);
#line 178 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestFind(const string test_name);
#line 196 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestRemove_Node(const int count);
#line 242 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestRemove_Max(const int count);
#line 270 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestRemove_Min(const int count);
#line 298 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
bool TestRemove(const string test_name);
#line 320 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestRedBlackTree.mq5"
void TestRedBlackTree(int &tests_performed, int &tests_passed);

#endif
