#ifndef MQL_AUTO_FORWARDS_INCLUDED_9C783A9B3B0397B9
#define MQL_AUTO_FORWARDS_INCLUDED_9C783A9B3B0397B9
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
include <Generic\ArrayList.mqh> bool TestConstructor_Valid(const int count);
#line 49 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestConstructor_Invalid(const int count);
#line 65 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestConstructor(const string test_name);
#line 83 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestMisc_Pop(const int count);
#line 105 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestMisc_Peek(const int count);
#line 126 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestMisc_Complex(const int count);
#line 160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestMisc_TrimExcess(const int count);
#line 198 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
bool TestMisc(const string test_name);
#line 224 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestStack.mq5"
void TestStack(int &tests_performed, int &tests_passed);

#endif
