#ifndef MQL_AUTO_FORWARDS_INCLUDED_455351C028169740
#define MQL_AUTO_FORWARDS_INCLUDED_455351C028169740
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5

#line 690 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
int GetCorrectDigits(const double delta);
#line 721 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestBinomialDistribution(string test_name, const double n, const double probability, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 905 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestBetaDistribution(string test_name, const double a, const double b, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 1089 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestGammaDistribution(string test_name, const double a, const double b, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 1273 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestCauchyDistribution(string test_name, const double a, const double b, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 1451 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestExponentialDistribution(string test_name, const double mu, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 1635 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestUnifromDistribution(string test_name, const double a, const double b, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 1819 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestGeometricDistribution(string test_name, const double p, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2003 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestHypergeometricDistribution(string test_name, const double m, const double k, const double n, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2187 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestLogisticDistribution(string test_name, const double mu, const double sigma, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2371 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestWeibullDistribution(string test_name, const double a, const double b, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2555 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestPoissonDistribution(string test_name, const double lambda, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2739 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestFDistribution(string test_name, const double nu1, const double nu2, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 2924 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestChiSquareDistribution(string test_name, const double nu, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 3108 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNoncentralChiSquareDistribution(string test_name, const double nu, const double sigma, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 3293 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNoncentralFDistribution(string test_name, const double nu1, const double nu2, const double sigma, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 3478 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNoncentralBetaDistribution(string test_name, const double a, const double b, const double lambda, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 3663 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNegativeBinomialDistribution(string test_name, const double r, const double p, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 3847 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestTDistribution(string test_name, const double nu, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 4031 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNoncentralTDistribution(string test_name, const double nu, const double delta, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 4215 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestNormalDistribution(string test_name, const double mu, const double sigma, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 4400 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
bool TestLognormalDistribution(string test_name, const double mu, const double sigma, const double &x_values[], const double &pdf_values[], const double &cdf_values[], precision_info &precision);
#line 4584 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
void ShowPrecisionInfo(const string distribution, precision_info &precision);
#line 4596 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
void TestDistributions(int &tests_performed, int &tests_passed);
#line 4837 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStat.mq5"
void UnitTests(const string package_name);

#endif
