#ifndef MQL_AUTO_FORWARDS_INCLUDED_26E8C7D11100899F
#define MQL_AUTO_FORWARDS_INCLUDED_26E8C7D11100899F
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/TestBot.mq5

#line 92 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/TestBot.mq5"
int ChartVisibleBars(const long chart_ID);

#endif
