#ifndef MQL_AUTO_FORWARDS_INCLUDED_EDBB23A974D737D1
#define MQL_AUTO_FORWARDS_INCLUDED_EDBB23A974D737D1
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5"
include <Generic\HashMap.mqh> bool TestMisc_Constructor(const int count);
#line 43 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5"
bool TestMisc_Contains(const int count);
#line 86 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5"
bool TestMisc_Remove(const int count);
#line 137 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5"
bool TestMisc(const string test_name);
#line 159 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashMap.mq5"
void TestHashMap(int &tests_performed, int &tests_passed);

#endif
