#ifndef MQL_AUTO_FORWARDS_INCLUDED_146178F7D75DA977
#define MQL_AUTO_FORWARDS_INCLUDED_146178F7D75DA977
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Alglib/TestClasses.mq5

#line 708 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Alglib/TestClasses.mq5"
string GetElapsed(ulong microseconds);

#endif
