#ifndef MQL_AUTO_FORWARDS_INCLUDED_797FCD94B0E7EE3F
#define MQL_AUTO_FORWARDS_INCLUDED_797FCD94B0E7EE3F
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
include <Generic\HashSet.mqh> bool TestAddRange_AsArrayList(const int count, const int add_length);
#line 51 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestAddRange_AsArray(const int count, const int add_length);
#line 90 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestAddRange_AsNULL(const int count);
#line 121 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestAddRange(const string test_name);
#line 143 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestBinarySearch_Validations(const int count);
#line 177 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestBinarySearch_WithoutDuplicates(const int count);
#line 201 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestBinarySearch_WithDuplicates(const int count);
#line 227 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestBinarySearch(const string test_name);
#line 249 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestIndexOf_NonExistingValues(const int count);
#line 268 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestIndexOf_OrderIsCorrect(const int count);
#line 300 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestIndexOf_Common(const int count);
#line 336 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestIndexOf_OutOfRange(const int count);
#line 361 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestIndexOf(const string test_name);
#line 387 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc_BasicInsert(const int count);
#line 449 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc_InsertRange(const int count);
#line 526 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc_Contains(const int count);
#line 545 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc_Remove(const int count);
#line 568 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc_Clear(const int count);
#line 594 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestMisc(const string test_name);
#line 624 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestRemove_Range(const int count);
#line 680 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestRemove_Invalid(const int count);
#line 747 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestRemove(const string test_name);
#line 765 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestReverse_Range(const int count);
#line 829 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestReverse_Invalid(const int count);
#line 893 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestReverse(const string test_name);
#line 911 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestSort_WithDuplicates(const int count);
#line 941 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestSort_Invalid(const int count);
#line 976 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
bool TestSort(const string test_name);
#line 994 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestArrayList.mq5"
void TestArrayList(int &tests_performed, int &tests_passed);

#endif
