#ifndef MQL_AUTO_FORWARDS_INCLUDED_01A3B4CA4CF9F9BC
#define MQL_AUTO_FORWARDS_INCLUDED_01A3B4CA4CF9F9BC
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
include <Generic\ArrayList.mqh> bool TestAddAfter_Node(const int count);
#line 213 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddAfter_Node_Negative(const int count);
#line 256 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddAfter(const string test_name);
#line 275 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddBefore_Node(const int count);
#line 482 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddBefore_Node_Negative(const int count);
#line 525 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddBefore(const string test_name);
#line 544 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddFirst_Node(const int count);
#line 678 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddFirst_Node_Negative(const int count);
#line 733 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddFirst(const string test_name);
#line 751 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddLast_Node(const int count);
#line 872 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddLast_Node_Negative(const int count);
#line 927 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestAddLast(const string test_name);
#line 945 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestConstructor_Complex(const int count);
#line 980 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestConstructor(const string test_name);
#line 994 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc_Find(const int count);
#line 1160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc_FindLast(const int count);
#line 1326 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc_RemoveNode(const int count);
#line 1646 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc_RemoveFirst(const int count);
#line 1770 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc_RemoveLast(const int count);
#line 1899 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
bool TestMisc(const string test_name);
#line 1929 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestLinkedList.mq5"
void TestLinkedList(int &tests_performed, int &tests_passed);

#endif
