#ifndef MQL_AUTO_FORWARDS_INCLUDED_151D3BF9D63FF2C8
#define MQL_AUTO_FORWARDS_INCLUDED_151D3BF9D63FF2C8
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashSet.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashSet.mq5"
include <Generic\HashSet.mqh> bool TestMisc_Constructor(const int count);
#line 42 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashSet.mq5"
bool TestMisc_TrimExpress(const int count);
#line 102 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashSet.mq5"
bool TestMisc(const string test_name);
#line 120 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestHashSet.mq5"
void TestHashSet(int &tests_performed, int &tests_passed);

#endif
