#ifndef MQL_AUTO_FORWARDS_INCLUDED_F0DF0A8E0CF7CAF3
#define MQL_AUTO_FORWARDS_INCLUDED_F0DF0A8E0CF7CAF3
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5"
include <Generic\SortedMap.mqh> bool TestMisc_Constructor(const int count);
#line 43 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5"
bool TestMisc_Contains(const int count);
#line 86 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5"
bool TestMisc_Ordering(const int count);
#line 138 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5"
bool TestMisc(const string test_name);
#line 160 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedMap.mq5"
void TestSortedMap(int &tests_performed, int &tests_passed);

#endif
