#ifndef MQL_AUTO_FORWARDS_INCLUDED_414528A4786D2524
#define MQL_AUTO_FORWARDS_INCLUDED_414528A4786D2524
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStatPrecision.mq5

#line 80 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStatPrecision.mq5"
int GetCorrectDigits(const double delta);
#line 101 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Stat/TestStatPrecision.mq5"
void TestPrecision(const string comment, const double pdf, const double cdf, const double pdf_calculated, const double cdf_calculated);

#endif
