#ifndef MQL_AUTO_FORWARDS_INCLUDED_7ACED1765A3CD477
#define MQL_AUTO_FORWARDS_INCLUDED_7ACED1765A3CD477
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/test2.mq5

#line 40 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/test2.mq5"
void OnNewBarClosed(const MqlRates &newBar);
#line 44 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/test2.mq5"
MqlRates GetLastClosedBar();

#endif
