#ifndef MQL_AUTO_FORWARDS_INCLUDED_015AA37A6C720B50
#define MQL_AUTO_FORWARDS_INCLUDED_015AA37A6C720B50
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedSet.mq5

#line 11 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedSet.mq5"
include <Generic\SortedSet.mqh> bool TestMisc_Constructor(const int count);
#line 54 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedSet.mq5"
bool TestMisc_GetViewBetween(const int count);
#line 102 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedSet.mq5"
bool TestMisc(const string test_name);
#line 120 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/UnitTests/Generic/TestSortedSet.mq5"
void TestSortedSet(int &tests_performed, int &tests_passed);

#endif
