#ifndef MQL_AUTO_FORWARDS_INCLUDED_3798140965A6F936
#define MQL_AUTO_FORWARDS_INCLUDED_3798140965A6F936
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/TRIX.mq5


#endif
