#ifndef MQL_AUTO_FORWARDS_INCLUDED_8D90690C1B3E5D32
#define MQL_AUTO_FORWARDS_INCLUDED_8D90690C1B3E5D32
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/VIDYA.mq5

#line 77 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/VIDYA.mq5"
double CalculateCMO(int pos, const int period, const double &price[]);

#endif
