#ifndef MQL_AUTO_FORWARDS_INCLUDED_9C13EA040F8BB585
#define MQL_AUTO_FORWARDS_INCLUDED_9C13EA040F8BB585
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Volumes.mq5

#line 70 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/Volumes.mq5"
void CalculateVolume(const int pos, const int rates_total, const long& volume[]);

#endif
