#ifndef MQL_AUTO_FORWARDS_INCLUDED_78C3ED019DEB3DD8
#define MQL_AUTO_FORWARDS_INCLUDED_78C3ED019DEB3DD8
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/VROC.mq5

#line 85 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/VROC.mq5"
void CalculateVROC(const int pos, const int rates_total, const long& volume[]);

#endif
