#ifndef MQL_AUTO_FORWARDS_INCLUDED_2D4AA7E4AF561EED
#define MQL_AUTO_FORWARDS_INCLUDED_2D4AA7E4AF561EED
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/W_AD.mq5

#line 83 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/W_AD.mq5"
bool IsEqualDoubles(double d1, double d2, double epsilon);

#endif
