#ifndef MQL_AUTO_FORWARDS_INCLUDED_408B282B3E06A126
#define MQL_AUTO_FORWARDS_INCLUDED_408B282B3E06A126
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Double/Wavelet.mq5

#line 294 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Double/Wavelet.mq5"
double Weirstrass(double x, double a, double b);
#line 311 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Double/Wavelet.mq5"
void PrepareModelData(double &price_data[], const int datacount);
#line 326 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Double/Wavelet.mq5"
void PreparePriceData(const string symbol, ENUM_TIMEFRAMES timeframe, double &price_data[], const int datacount);
#line 334 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Double/Wavelet.mq5"
void PrepareMomentumData(double &price_data[], double &momentum_data[], const int momentum_period);

#endif
