#ifndef MQL_AUTO_FORWARDS_INCLUDED_D2AD4149B16C89A5
#define MQL_AUTO_FORWARDS_INCLUDED_D2AD4149B16C89A5
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/Wavelet.mq5

#line 288 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/Wavelet.mq5"
float Weirstrass(float x, float a, float b);
#line 305 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/Wavelet.mq5"
void PrepareModelData(float &price_data[], const int datacount);
#line 320 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/Wavelet.mq5"
void PreparePriceData(const string symbol, ENUM_TIMEFRAMES timeframe, float &price_data[], const int datacount);
#line 336 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Scripts/Examples/OpenCL/Float/Wavelet.mq5"
void PrepareMomentumData(float &price_data[], float &momentum_data[], const int momentum_period);

#endif
