#ifndef MQL_AUTO_FORWARDS_INCLUDED_CC9AEE8C8CAC4768
#define MQL_AUTO_FORWARDS_INCLUDED_CC9AEE8C8CAC4768
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/WPR.mq5

#line 90 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/WPR.mq5"
double Highest(const double &array[], int period, int cur_position);
#line 101 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/WPR.mq5"
double Lowest(const double &array[], int period, int cur_position);

#endif
