#ifndef MQL_AUTO_FORWARDS_INCLUDED_65B08D99FC45CB53
#define MQL_AUTO_FORWARDS_INCLUDED_65B08D99FC45CB53
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigzagColor.mq5

#line 264 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigzagColor.mq5"
double Highest(const double&array[], int count, int start);
#line 277 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigzagColor.mq5"
double Lowest(const double&array[], int count, int start);

#endif
