#ifndef MQL_AUTO_FORWARDS_INCLUDED_C63BBE2B433E2FB0
#define MQL_AUTO_FORWARDS_INCLUDED_C63BBE2B433E2FB0
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigZag.mq5

#line 253 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigZag.mq5"
int Highest(const double &array[], const int depth, const int start);
#line 275 "c:/Users/PC/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/Examples/ZigZag.mq5"
int Lowest(const double &array[], const int depth, const int start);

#endif
